-- Create simple cart table without RLS policies
CREATE TABLE public.cart (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    products json NULL,
    name text NULL,
    email text NULL,
    CONSTRAINT cart_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- No RLS policies - table is open for authenticated users
-- Access control is handled by filtering on email in application code