-- Create Orders table
CREATE TABLE public."Orders" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending',
    total_amount numeric NOT NULL DEFAULT 0,
    shipping_cost numeric NOT NULL DEFAULT 0,
    
    -- Customer details
    first_name text NOT NULL,
    last_name text NOT NULL,
    company_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    iec_tax_id text NULL,
    
    -- Shipping details
    shipping_address text NOT NULL,
    city text NOT NULL,
    country text NOT NULL,
    incoterms text NOT NULL,
    special_instructions text NULL,
    
    CONSTRAINT Orders_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create Order Items table
CREATE TABLE public."OrderItems" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    order_id bigint REFERENCES public."Orders"(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public."Products"(id) ON DELETE CASCADE,
    quantity bigint NOT NULL,
    unit_price numeric NOT NULL,
    total_price numeric NOT NULL,
    
    CONSTRAINT OrderItems_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Enable Row Level Security
ALTER TABLE public."Orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OrderItems" ENABLE ROW LEVEL SECURITY;

-- Create policies for Orders
CREATE POLICY "Users can view their own orders" ON public."Orders"
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own orders" ON public."Orders"
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own orders" ON public."Orders"
FOR UPDATE USING (auth.uid() = user_id);

-- Create policies for OrderItems
CREATE POLICY "Users can view their own order items" ON public."OrderItems"
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public."Orders" 
        WHERE id = order_id AND user_id = auth.uid()
    )
);

CREATE POLICY "Users can create order items for their orders" ON public."OrderItems"
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public."Orders" 
        WHERE id = order_id AND user_id = auth.uid()
    )
);

-- Create function to update product stock
CREATE OR REPLACE FUNCTION update_product_stock()
RETURNS TRIGGER AS $$
BEGIN
    -- Reduce stock when order item is created
    IF TG_OP = 'INSERT' THEN
        UPDATE public."Products" 
        SET stock = stock - NEW.quantity
        WHERE id = NEW.product_id;
        
        -- Check if stock goes negative
        IF (SELECT stock FROM public."Products" WHERE id = NEW.product_id) < 0 THEN
            RAISE EXCEPTION 'Insufficient stock for product ID %', NEW.product_id;
        END IF;
        
        RETURN NEW;
    END IF;
    
    -- Restore stock when order item is deleted (if order is cancelled)
    IF TG_OP = 'DELETE' THEN
        UPDATE public."Products" 
        SET stock = stock + OLD.quantity
        WHERE id = OLD.product_id;
        
        RETURN OLD;
    END IF;
    
    -- Handle stock changes when quantity is updated
    IF TG_OP = 'UPDATE' THEN
        UPDATE public."Products" 
        SET stock = stock + OLD.quantity - NEW.quantity
        WHERE id = NEW.product_id;
        
        -- Check if stock goes negative
        IF (SELECT stock FROM public."Products" WHERE id = NEW.product_id) < 0 THEN
            RAISE EXCEPTION 'Insufficient stock for product ID %', NEW.product_id;
        END IF;
        
        RETURN NEW;
    END IF;
    
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update stock
CREATE TRIGGER trigger_update_product_stock
    AFTER INSERT OR UPDATE OR DELETE ON public."OrderItems"
    FOR EACH ROW
    EXECUTE FUNCTION update_product_stock();

-- Create function to calculate order total
CREATE OR REPLACE FUNCTION calculate_order_total()
RETURNS TRIGGER AS $$
BEGIN
    -- Update order total when order items change
    UPDATE public."Orders" 
    SET total_amount = (
        SELECT COALESCE(SUM(total_price), 0) 
        FROM public."OrderItems" 
        WHERE order_id = COALESCE(NEW.order_id, OLD.order_id)
    )
    WHERE id = COALESCE(NEW.order_id, OLD.order_id);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically calculate order totals
CREATE TRIGGER trigger_calculate_order_total
    AFTER INSERT OR UPDATE OR DELETE ON public."OrderItems"
    FOR EACH ROW
    EXECUTE FUNCTION calculate_order_total();