-- Create the contact_us table
CREATE TABLE IF NOT EXISTS public.contact_us (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  email text NULL,
  subject text NULL,
  message text NULL,
  CONSTRAINT contact_us_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Enable RLS (Row Level Security)
ALTER TABLE public.contact_us ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to insert contact queries
CREATE POLICY "Anyone can submit contact queries" ON public.contact_us
  FOR INSERT WITH CHECK (true);

-- Create policy to allow users to view their own contact queries (optional)
CREATE POLICY "Users can view their own contact queries" ON public.contact_us
  FOR SELECT USING (
    auth.jwt() ->> 'email' = email OR 
    auth.role() = 'service_role'
  );