-- Drop existing tables if they exist
DROP TABLE IF EXISTS public."Orders" CASCADE;
DROP TABLE IF EXISTS public."OrderItems" CASCADE;

-- Create the order table with the correct schema
CREATE TABLE IF NOT EXISTS public."order" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  email text NULL,
  products json NULL,
  number numeric NULL,
  "import export code" text NULL,
  "shipping address" text NULL,
  port text NULL,
  country text NULL,
  status text NULL,
  incoterms text NULL,
  instructions text NULL,
  total_amount numeric NULL,
  payment text NULL,
  CONSTRAINT orders_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Enable RLS (Row Level Security)
ALTER TABLE public."order" ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to see their own orders (based on email)
CREATE POLICY "Users can view their own orders" ON public."order"
  FOR SELECT USING (auth.jwt() ->> 'email' = email);

-- Create policy to allow users to insert their own orders
CREATE POLICY "Users can insert their own orders" ON public."order"
  FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = email);

-- Create policy to allow users to update their own orders
CREATE POLICY "Users can update their own orders" ON public."order"
  FOR UPDATE USING (auth.jwt() ->> 'email' = email);