-- Create Products table
CREATE TABLE public."Products" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NULL,
    description text NULL,
    code character varying NULL,
    stock bigint NULL,
    price numeric NULL,
    img text NULL,
    CONSTRAINT Products_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Enable Row Level Security
ALTER TABLE public."Products" ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access to all users
CREATE POLICY "Allow read access to all users" ON public."Products"
FOR SELECT USING (true);

-- Create policy to allow insert/update/delete for authenticated users (for admin purposes)
CREATE POLICY "Allow full access to authenticated users" ON public."Products"
FOR ALL USING (auth.role() = 'authenticated');

-- Insert some sample products
INSERT INTO public."Products" (name, description, code, stock, price, img) VALUES
('Premium Basmati Rice', 'Aromatic long-grain rice from the foothills of the Himalayas. Known for its distinctive fragrance and fluffy texture when cooked.', 'RICE-BAS-001', 5000, 850.00, 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=600&fit=crop'),
('Organic Turmeric Powder', 'Pure organic turmeric powder with high curcumin content. Sourced from certified organic farms in South India.', 'SPICE-TUR-001', 2500, 1200.00, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&h=600&fit=crop'),
('Red Chili Powder', 'Premium quality red chili powder with perfect heat and color. Made from sun-dried red chilies.', 'SPICE-CHI-001', 3000, 950.00, 'https://images.unsplash.com/photo-1583032015870-403e9c5ae4b4?w=800&h=600&fit=crop'),
('Black Pepper Whole', 'Premium black peppercorns from the Western Ghats. Known for their strong aroma and pungent flavor.', 'SPICE-PEP-001', 1500, 2200.00, 'https://images.unsplash.com/photo-1599909533730-8b9e1b7b4b4a?w=800&h=600&fit=crop'),
('Cardamom Green', 'Premium green cardamom pods with intense aroma. Hand-picked from the hills of Kerala.', 'SPICE-CAR-001', 800, 4500.00, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=600&fit=crop'),
('Coriander Seeds', 'High-quality coriander seeds with excellent aroma. Perfect for grinding into powder or using whole.', 'SPICE-COR-001', 2000, 750.00, 'https://images.unsplash.com/photo-1599909533730-8b9e1b7b4b4a?w=800&h=600&fit=crop'),
('Cumin Seeds', 'Premium cumin seeds with strong flavor profile. Essential spice for Indian and Middle Eastern cuisine.', 'SPICE-CUM-001', 1800, 1100.00, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=600&fit=crop'),
('Fenugreek Seeds', 'High-quality fenugreek seeds with bitter-sweet flavor. Used in spice blends and traditional medicine.', 'SPICE-FEN-001', 1200, 900.00, 'https://images.unsplash.com/photo-1583032015870-403e9c5ae4b4?w=800&h=600&fit=crop'),
('Mustard Seeds Yellow', 'Premium yellow mustard seeds with mild flavor. Perfect for tempering and oil extraction.', 'SPICE-MUS-001', 2200, 650.00, 'https://images.unsplash.com/photo-1599909533730-8b9e1b7b4b4a?w=800&h=600&fit=crop'),
('Sesame Seeds White', 'High-quality white sesame seeds with nutty flavor. Rich in healthy oils and nutrients.', 'SEED-SES-001', 1600, 800.00, 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=600&fit=crop'),
('Chickpeas (Kabuli)', 'Premium quality chickpeas with uniform size. High protein content and excellent cooking quality.', 'PULSE-CHI-001', 4000, 720.00, 'https://images.unsplash.com/photo-1583032015870-403e9c5ae4b4?w=800&h=600&fit=crop'),
('Red Lentils', 'High-quality red lentils that cook quickly. Rich in protein and perfect for dal preparations.', 'PULSE-LEN-001', 3500, 680.00, 'https://images.unsplash.com/photo-1599909533730-8b9e1b7b4b4a?w=800&h=600&fit=crop');