-- Create Cart table
CREATE TABLE public.cart (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    product json NULL,
    name text NULL,
    email text NULL,
    CONSTRAINT cart_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Enable Row Level Security
ALTER TABLE public.cart ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to manage their own cart items
CREATE POLICY "Users can manage their own cart items" ON public.cart
FOR ALL USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
);

-- Create policy to allow read access based on email
CREATE POLICY "Users can read their own cart items" ON public.cart
FOR SELECT USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
);

-- Create policy to allow insert with user's email
CREATE POLICY "Users can insert their own cart items" ON public.cart
FOR INSERT WITH CHECK (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
);

-- Create policy to allow update of their own cart items
CREATE POLICY "Users can update their own cart items" ON public.cart
FOR UPDATE USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
);

-- Create policy to allow delete of their own cart items
CREATE POLICY "Users can delete their own cart items" ON public.cart
FOR DELETE USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
);