-- Create payments table to track Razorpay transactions
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  
  -- Order reference
  order_id bigint REFERENCES public."order"(id) ON DELETE CASCADE,
  
  -- User reference
  user_email text NOT NULL,
  
  -- Razorpay details
  razorpay_order_id text NOT NULL,
  razorpay_payment_id text NULL,
  razorpay_signature text NULL,
  
  -- Payment details
  amount numeric NOT NULL, -- Amount in paise (INR * 100)
  currency text NOT NULL DEFAULT 'INR',
  status text NOT NULL DEFAULT 'created', -- created, paid, failed, cancelled
  
  -- Additional info
  payment_method text NULL,
  failure_reason text NULL,
  notes jsonb NULL,
  
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT unique_razorpay_order_id UNIQUE (razorpay_order_id)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own payments" ON public.payments
  FOR SELECT USING (auth.jwt() ->> 'email' = user_email);

CREATE POLICY "Users can insert their own payments" ON public.payments
  FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = user_email);

CREATE POLICY "Users can update their own payments" ON public.payments
  FOR UPDATE USING (auth.jwt() ->> 'email' = user_email);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updated_at
CREATE TRIGGER update_payments_updated_at 
    BEFORE UPDATE ON public.payments 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();