-- Clean up any old migration artifacts
-- Drop functions and triggers from old schema if they exist
DROP TRIGGER IF EXISTS trigger_update_product_stock ON public."OrderItems";
DROP TRIGGER IF EXISTS trigger_calculate_order_total ON public."OrderItems";
DROP FUNCTION IF EXISTS update_product_stock();
DROP FUNCTION IF EXISTS calculate_order_total();

-- Drop old tables if they still exist
DROP TABLE IF EXISTS public."Orders" CASCADE;
DROP TABLE IF EXISTS public."OrderItems" CASCADE;

-- Ensure the correct table exists with proper structure
-- This is idempotent - won't fail if table already exists
CREATE TABLE IF NOT EXISTS public."order" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  email text NULL,
  products json NULL,
  number numeric NULL,
  "import export code" text NULL,
  "shipping address" text NULL,
  port text NULL,
  country text NULL,
  status text NULL,
  incoterms text NULL,
  instructions text NULL,
  total_amount numeric NULL,
  payment text NULL,
  CONSTRAINT orders_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;